# Generated by Django 5.2.1 on 2025-06-30 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0003_projectpdffile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionalFieldRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_value', models.CharField(help_text="Valeur qui déclenche l'apparition du champ conditionnel", max_length=100)),
                ('conditional_field_name', models.CharField(help_text='Nom technique du champ conditionnel', max_length=100)),
                ('conditional_field_label', models.CharField(help_text='Label affiché du champ conditionnel', max_length=200)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conditional_rules', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('parent_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditional_rules', to='database.dynamicfield')),
                ('parent_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditional_rules', to='database.dynamictable')),
                ('source_field', models.ForeignKey(blank=True, help_text='Champ source pour les options', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sourced_conditional_rules', to='database.dynamicfield')),
                ('source_table', models.ForeignKey(blank=True, help_text='Table source pour les options (ex: table Choix)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sourced_conditional_rules', to='database.dynamictable')),
            ],
            options={
                'verbose_name': 'Règle de champ conditionnel',
                'verbose_name_plural': 'Règles de champs conditionnels',
                'ordering': ['order', 'conditional_field_label'],
                'unique_together': {('parent_table', 'parent_field', 'parent_value', 'conditional_field_name')},
            },
        ),
        migrations.CreateModel(
            name='ConditionalFieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text="Valeur technique de l'option", max_length=100)),
                ('label', models.CharField(help_text="Label affiché de l'option", max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conditional_options', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('conditional_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='conditional_fields.conditionalfieldrule')),
            ],
            options={
                'verbose_name': 'Option de champ conditionnel',
                'verbose_name_plural': 'Options de champs conditionnels',
                'ordering': ['order', 'label'],
                'unique_together': {('conditional_rule', 'value')},
            },
        ),
    ]
