services:
  backend:
    image: finnick5/cochin-project-manager-backend:latest
    container_name: cochin_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data/db:/app/data/db
      - ./data/media:/app/media
      - ./data/backups:/app/backups
      - ./data/logs:/app/logs
      - ./data/staticfiles:/app/staticfiles
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DJANGO_ENV=production
      - DJANGO_SETTINGS_MODULE=app.settings
      - SECRET_KEY=django_secure_key
      - BACKUP_ENCRYPTION_KEY=backup_key_to_set
      - DISCORD_WEBHOOK_URL=url_webhook
      - ALLOWED_HOSTS=project-manager.local,localhost,127.0.0.1
      - CORS_ALLOWED_ORIGINS=http://project-manager.local,https://project-manager.local
      - CSRF_TRUSTED_ORIGINS=http://project-manager.local,https://project-manager.local
      - FORCE_SSL=true
      - DEBUG=False
    networks:
      - cochin_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  frontend:
    image: finnick5/cochin-project-manager-frontend:latest
    container_name: cochin_frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/staticfiles:/usr/share/nginx/html/static:ro
      - ./data/media:/usr/share/nginx/html/media:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - cochin_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  cochin_network:
    driver: bridge

volumes:
  staticfiles:
  media: 