# Fichier de raccourci - Le vrai docker-compose.yml est dans docker/compose/
# 
# Pour développement local, utilisez :
# docker-compose -f docker/compose/docker-compose.local.yml up --build
#
# Pour production, utilisez :
# docker-compose -f docker/compose/docker-compose.prod.yml up --build
#
# Pour un déploiement minimal :
# docker-compose -f docker/compose/deploy-minimal.yml up --build

# Ce fichier redirige vers la configuration de développement local par défaut
include:
  - docker/compose/docker-compose.local.yml 