# Generated by Django 5.2.1 on 2025-06-30 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_add_discord_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPdfFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255, verbose_name='nom du fichier original')),
                ('display_name', models.CharField(help_text="Nom personnalisé pour l'affichage", max_length=255, verbose_name="nom d'affichage")),
                ('file', models.FileField(help_text='Fichier PDF du projet', upload_to='project_pdfs/%Y/%m/', verbose_name='fichier PDF')),
                ('file_size', models.BigIntegerField(help_text='Taille en bytes', verbose_name='taille du fichier')),
                ('description', models.TextField(blank=True, help_text='Description optionnelle du document', verbose_name='description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploadé le')),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage des fichiers", verbose_name='ordre')),
                ('project_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_files', to='database.dynamicrecord', verbose_name='projet')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='uploadé par')),
            ],
            options={
                'verbose_name': 'fichier PDF de projet',
                'verbose_name_plural': 'fichiers PDF de projet',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
