version: '3.8'

services:
  backend:
    image: finnick5/cochin-project-manager-backend:latest
    container_name: cochin_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ../../data/db:/app/data/db
      - ../../data/media:/app/media
      - ../../data/backups:/app/backups
      - ../../data/logs:/app/logs
      - ../../data/staticfiles:/app/staticfiles
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
      - SECRET_KEY=${SECRET_KEY:-django-insecure-change-this-in-production-12345}
      - BACKUP_ENCRYPTION_KEY=${BACKUP_ENCRYPTION_KEY:-change-this-key-in-production}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL:-}
      - ALLOWED_HOSTS=localhost,127.0.0.1,*
      - CORS_ALLOWED_ORIGINS=*
      - DEBUG=False
      - AUTO_INIT=true
    networks:
      - cochin_network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8000/api/health/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s

  frontend:
    image: finnick5/cochin-project-manager-frontend:latest
    container_name: cochin_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ../../data/staticfiles:/usr/share/nginx/html/static:ro
      - ../../data/media:/usr/share/nginx/html/media:ro
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - cochin_network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  cochin_network:
    driver: bridge 