# Generated by Django 5.2.1 on 2025-06-19 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    
    initial = True

    operations = [
        migrations.CreateModel(
            name='UploadedBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nom du fichier original')),
                ('upload_name', models.CharField(max_length=200, verbose_name="Nom d'identification")),
                ('file_path', models.CharField(max_length=500, verbose_name='Chemin du fichier uploadé')),
                ('file_size', models.BigIntegerField(verbose_name='Taille (bytes)')),
                ('file_checksum', models.CharField(max_length=64, verbose_name='Checksum SHA-256')),
                ('status', models.CharField(choices=[('processing', 'Traitement en cours'), ('validated', 'Validée'), ('ready', 'Prête pour restauration'), ('failed_validation', 'Validation échouée'), ('corrupted', 'Fichier corrompu')], db_index=True, default='processing', max_length=20)),
                ('validation_data', models.JSONField(blank=True, default=dict, verbose_name='Données de validation')),
                ('backup_metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées extraites')),
                ('detected_backup_type', models.CharField(blank=True, max_length=20)),
                ('detected_source_system', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('error_message', models.TextField(blank=True)),
                ('processing_log', models.JSONField(blank=True, default=list)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sauvegarde uploadée',
                'verbose_name_plural': 'Sauvegardes uploadées',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalRestoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restoration_name', models.CharField(max_length=200, verbose_name='Nom de la restauration')),
                ('merge_strategy', models.CharField(choices=[('replace', 'Remplacement complet'), ('merge', 'Fusion intelligente'), ('preserve_system', 'Préserver les données système')], default='preserve_system', max_length=20, verbose_name='Stratégie de fusion')),
                ('restoration_options', models.JSONField(blank=True, default=dict, help_text='Options spécifiques pour cette restauration externe')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('extracting', 'Extraction en cours'), ('analyzing', 'Analyse du contenu'), ('executing', 'Exécution de la restauration'), ('finalizing', 'Finalisation'), ('completed', 'Terminée'), ('failed', 'Échouée'), ('cancelled', 'Annulée')], db_index=True, default='pending', max_length=20)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('current_step', models.CharField(blank=True, max_length=100)),
                ('external_tables_processed', models.PositiveIntegerField(blank=True, null=True)),
                ('external_records_processed', models.PositiveIntegerField(blank=True, null=True)),
                ('external_files_processed', models.PositiveIntegerField(blank=True, null=True)),
                ('system_tables_preserved', models.PositiveIntegerField(blank=True, null=True)),
                ('conflicts_resolved', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('execution_log', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('rollback_info', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_restorations', to=settings.AUTH_USER_MODEL)),
                ('uploaded_backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_restorations', to='backup_manager.uploadedbackup')),
            ],
            options={
                'verbose_name': 'Restauration externe',
                'verbose_name_plural': 'Restaurations externes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='uploadedbackup',
            index=models.Index(fields=['status', 'uploaded_at'], name='upload_status_date'),
        ),
        migrations.AddIndex(
            model_name='uploadedbackup',
            index=models.Index(fields=['uploaded_by', 'status'], name='upload_user_status'),
        ),
        migrations.AddIndex(
            model_name='externalrestoration',
            index=models.Index(fields=['status', 'created_at'], name='ext_restore_status'),
        ),
        migrations.AddIndex(
            model_name='externalrestoration',
            index=models.Index(fields=['merge_strategy', 'status'], name='ext_merge_status'),
        ),
    ]
